// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7iPVAs4PG10NpPe9IG95nuyTmZOU8weU',
    appId: '1:584734272652:web:b13e4d50578672537b9fa9',
    messagingSenderId: '584734272652',
    projectId: 'galleryapp-84799',
    authDomain: 'galleryapp-84799.firebaseapp.com',
    storageBucket: 'galleryapp-84799.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQTvkXsO6dngnHFzgth6eLf0u0SqD3U68',
    appId: '1:584734272652:android:15d0301575a0831b7b9fa9',
    messagingSenderId: '584734272652',
    projectId: 'galleryapp-84799',
    storageBucket: 'galleryapp-84799.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMic0IZk7vPHcsRcTrcrrts-dE4rpu668',
    appId: '1:584734272652:ios:f662b041f474ea257b9fa9',
    messagingSenderId: '584734272652',
    projectId: 'galleryapp-84799',
    storageBucket: 'galleryapp-84799.firebasestorage.app',
    iosBundleId: 'com.example.galleriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMic0IZk7vPHcsRcTrcrrts-dE4rpu668',
    appId: '1:584734272652:ios:f662b041f474ea257b9fa9',
    messagingSenderId: '584734272652',
    projectId: 'galleryapp-84799',
    storageBucket: 'galleryapp-84799.firebasestorage.app',
    iosBundleId: 'com.example.galleriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7iPVAs4PG10NpPe9IG95nuyTmZOU8weU',
    appId: '1:584734272652:web:40e97d24c765e8a17b9fa9',
    messagingSenderId: '584734272652',
    projectId: 'galleryapp-84799',
    authDomain: 'galleryapp-84799.firebaseapp.com',
    storageBucket: 'galleryapp-84799.firebasestorage.app',
  );
}
